variables:
  VERSION_ID: '1.0.$CI_PIPELINE_ID'

stages:
  - build

build:
  image: electronuserland/builder:wine
  stage: build
  script:
    - npm i
    - npm run package -- --linux
    - npm run package -- --windows
    # - npm run package -- --mac
    - mkdir .public
    - cp -r release/build/* .public
    - mv .public public
  dependencies:
    - build
  artifacts:
    paths:
      - public/*-mac.zip
      - public/*.exe
      - public/*.AppImage
  artifacts:
    expire_in: 30 days
    paths:
      - release/build/*-mac.zip
      - release/build/*.exe
  only:
    - master
