module.exports.locations = [
  "Austin, Texas",
  "San Jose, California",
  "Dallas, TX",
  "Atlanta, GA",
  "Huntsville, AL",
  "Charlotte, NC",
  "Raleigh, NC",
  "San Francisco, CA",
  "Seattle, WA",
  "Washington, D.C.",
  "Lansing, MI",
  "Baltimore, MD",
  "Durham-Chapel Hill, NC",
  "Trenton, NJ",
  "Boulder, CO",
  "New York City, NY",
  "Colorado Springs, CO",
  "Des Moines, IA",
  "Hartford, CT",
  "Tallahassee, FL",
  "Huntsville, AL",
  "Colorado Springs, CO",
  "Green Bay, WI",
  "San Jose, CA",
  "Boulder, CO",
  "Fayetteville, AR",
  "Naples, FL",
  "Austin, TX",
  "Boston, MA",
  "OKC, OK",
  "Norman, OK",
  "United States",
  "California",
  "Texas",
  "New York",
  "Tulsa, OK",
];
