module.exports.locations = [
	"Durham-Chapel Hill, NC",
	"Colorado Springs, CO",
	"San Jose, California",
	"San Francisco, CA",
	"New York City, NY",
	"Fayetteville, AR",
	"Washington, D.C.",
	"Tallahassee, FL",
	"Huntsville, AL",
	"Des Moines, IA",
	"Charlotte, NC",
	"Austin, Texas",
	"Baltimore, MD",
	"Green Bay, WI",
	"United States",
	"Hartford, CT",
	"San Jose, CA",
	"Atlanta, GA",
	"Raleigh, NC",
	"Seattle, WA",
	"Lansing, MI",
	"Trenton, NJ",
	"Boulder, CO",
	"Dallas, TX",
	"Naples, FL",
	"Austin, TX",
	"Boston, MA",
	"Norman, OK",
	"California",
	"Tulsa, OK",
	"OKC, OK",
	"New York",
	"Texas",
];
